### ISSUE TITLE
@textile/hub 1.2.0 - getOrCreate buckets produces mongo: no documents in result

### ISSUE THREAD

**Issue by jimmylee** [textileio/textile#421]
* This only seems to happen in the new @textile/hub 1.2.0
* For us, this happens for the create a bucket case
* This prevents us from launching 1.2.0

```
  const token = user.data.tokens.api;
  const name = Strings.isEmpty(bucketName) ? BUCKET_NAME : bucketName;
  const identity = await PrivateKey.fromString(token);
  let buckets = await Buckets.withKeyInfo(TEXTILE_KEY_INFO);

  await buckets.getToken(identity);  

  console.log(`[ buckets ] getOrCreate init ${name}`);
  let root = null;
  try {
    const creation = await buckets.getOrCreate(name, encrypted);
    root = creation.root;
  } catch (e) {
    console.log(e);
  }
```

Results in this output:

```
[ buckets ] getOrCreate init data
Error: mongo: no documents in result
    at Buckets.<anonymous> (/Users/riverlands/Development/slate/node_modules/@textile/buckets/src/buckets.ts:330:17)
    at Generator.throw (<anonymous>)
    at rejected (/Users/riverlands/Development/slate/node_modules/@textile/buckets/dist/buckets.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
POST /api/users/create 500 55 - 3338.545 ms
```

**Comment by jimmylee** [comment]
Looks like this bug is in production and it doesn't matter which version we use.

**Comment by jimmylee** [comment]
Better report:

```
(node:54785) UnhandledPromiseRejectionWarning: Error: mongo: no documents in result
    at Buckets.<anonymous> (/Users/riverlands/Development/slate/node_modules/@textile/buckets/src/buckets.ts:330:17)
    at Generator.throw (<anonymous>)
    at rejected (/Users/riverlands/Development/slate/node_modules/@textile/buckets/dist/buckets.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:54785) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by jimmylee** [comment]
This also happens for @textile/hub 1.2.0 (locally) and @textile/hub 1.1.1 production (we haven't deployed yet), so I'm taking Slate down by deploying the maintenance screen.

**Comment by jimmylee** [comment]
The issue is resolved by logging into your hub account again. If you don't, the keys wont work. If you do, all of your keys will work again.
